---
- name: Install mysql
  apt: name={{ item }} state=latest
  with_items:
    - libmysqld-dev

- name: Install rails and bundler
  sudo_user: "{{ rbenv_user }}"
  gem: name={{ item }} executable=.rbenv/shims/gem user_install=False
  with_items:
    - rails
    - bundler

- name: Install javascript tools
  npm: name={{ item }} state=latest global=yes
  with_items:
    - bower
    - grunt-cli

- name: Install ntp
  apt: name={{ item }} state=latest
  with_items:
    - ntp

- name: Set ntp service to start on boot
  service: name=ntp enabled=true

- name: Add repository for ansible
  apt_repository: repo='ppa:ansible/ansible' state=present

- name: Install ansible
  apt: name={{ item }} state=latest
  with_items:
    - ansible
